Approve all courses within department
TigerAppsOrg/TigerStudy pull request #9
Opened 2023-02-26 03:06 UTC by nicholaspad

## Summary

This PR adds the ability to approve all courses within a department. This means that students in study groups within previously-pending courses will get emails, as if each course was approved individually. In the "Admin Course View" page, each department has a new button:

<img width="1331" alt="CleanShot 2023-02-25 at 22 03 20@2x" src="https://user-images.githubusercontent.com/13815069/221390002-6352fdc7-9f83-4019-8fef-62ae0c2541d9.png">

This large diff in `admin_courses_new.html` is due to changing the `row`-`col` HTML structure.

I also fixed an issue with the admin edit course page not redirecting back to itself after clicking Submit.

## Demo

https://user-images.githubusercontent.com/13815069/221390005-abb2c3d3-0718-414c-9e56-ef4467ebdcd3.mp4

2023-02-27 18:55 UTC, shannon-heh requested changes

2023-02-27 18:55 UTC, shannon-heh commented on app.py
> +        print(all_dept_courses)
need to remove this `print` statement

2023-02-27 18:55 UTC, shannon-heh commented on app.py
> +            print("here")
and remove this `print`

2023-02-27 18:55 UTC, shannon-heh commented on static/admin.js
> +          `Failed to approve all courses in department ${dept} with error: "${res.error}".`
if it's easy, could you disable/remove the button if the course is already approved? only if it's easy to pass the approval status to the admin page

2023-02-27 18:55 UTC, shannon-heh commented on app.py
> +
what is this for?

2023-02-27 18:55 UTC, shannon-heh commented on app.py
> +                error=f"All study groups for department {dept} already approved",
Maybe add a statement: "No further action needed."

2023-02-27 18:55 UTC, shannon-heh commented on static/admin.js
> +      alert(`Failed to approve all courses in department ${dept}.`);
Maybe add a statement: "Students in department groups were not notified"

2023-02-28 22:40 UTC, nicholaspad commented on app.py
> +        print(all_dept_courses)
oops forgot about those... i just went ahead and removed all debugging print statements from the file

2023-02-28 22:45 UTC, nicholaspad commented on app.py
> +
it's to generate the `course` and `groups` data for `render_template` on line 809 so that the edit-course page can properly load

2023-02-28 23:36 UTC, nicholaspad commented on static/admin.js
> +          `Failed to approve all courses in department ${dept} with error: "${res.error}".`
done!

2023-02-28 23:37 UTC, nicholaspad commented
Approve-all buttons are now disabled if all courses in a department are already approved:


https://user-images.githubusercontent.com/13815069/222007654-6d5570a3-54ed-4eda-8826-8497e90be220.mp4

2023-03-09 21:01 UTC, shannon-heh approved these changes

2023-03-09 23:46 UTC, merged